name: Hai Job Release

on:
  push:
    tags:
      - 'hai-job-v*'

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Build Script
        shell: pwsh
        run: ./build_extension.ps1
      
      - name: Extract Version from Tag
        id: extract_version
        run: |
          TAG_NAME=${GITHUB_REF#refs/tags/}
          VERSION=${TAG_NAME#hai-job-v}
          echo "VERSION=$VERSION" >> $GITHUB_ENV
      - name: Extract Latest Release Notes
        run: |
          awk '
            /^## \[/ {
              if (in_section) { exit }
              in_section = 1; 
              next;
            }
            in_section { print }
          ' CHANGELOG.md > latest_release_notes.txt

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          name: "Hai Job Tracker v${{ env.VERSION }}"
          draft: false
          prerelease: false
          make_latest: true
          files: dist/hai_job_v${{ env.VERSION }}.zip
          body_path: latest_release_notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
